### ISSUE TITLE
Race condition when creating service too soon after create project

### ISSUE THREAD

**Issue by grabnerandi** [keptn-sandbox/keptn-jenkins-library#14]
We have seen this behavior with some of our users that the "create service" failed with a "project not found" error becuase the previous "create project" hasnt yet fully complete

This is part of the keptn.init function where project and service are created within a very short timeframe
I suggest we do some polling and retries first to avoid this issue

**Comment by christian-kreuzberger-dtx** [comment]
Cannot reproduce.
