### ISSUE TITLE
Custom Labels

### ISSUE THREAD

**Issue by leonvzGit** [keptn-sandbox/keptn-jenkins-library#5]
I would like to send through custom labels as part of the start evaluation event and this requirement will probably grow as we adopt more use cases. 
Specifically, I am using custom labels set at Jenkins job runtime in my SLI tags which the library doesn't cater for at the moment.

**Comment by grabnerandi** [comment]
This is now implemented in versions 2.2 and 3.2

**Comment by leonvzGit** [comment]
Thanks Andreas, I will test and send feedback asap
