### ISSUE TITLE
Jenkins job fails even if SLO Evalution passes keptn-library@2.2

### ISSUE THREAD

**Issue by leonvzGit** [keptn-sandbox/keptn-jenkins-library#6]
The Jenkins job fails even if the SLO Evaluation passes.
This happens when keptn.waitForEvaluationDoneEvent  is called with setBuildResult:true, 
line 660: error("Keptn Score: ${score}, Result: ${result}") 
this causes the the job to fail with call to error

keptn.waitForEvaluationDoneEvent returns the score and not the evaluation Result as pass/fail and therefore I cannot set the build result manually as a workaround , can we enhance this to return the Result and the score?

Tested with Jenkins ver. 2.121.3
Example from log:
`Archived Keptn Evaluation Done Result details in keptn.evaluationresult.9ae556dd-3295-4e6a-b47c-63a8b83af5e8.json
[Pipeline] readJSON
[Pipeline] echo
Retrieved Score: 91.666664, Result: pass
[Pipeline] catchError
[Pipeline] {
[Pipeline] error
[Pipeline] }
ERROR: Keptn Score: 91.666664, Result: pass
[Pipeline] // catchError
[Pipeline] echo
keptn result : 91.666664
[Pipeline] step
Processing provided DSL script
Existing user content:
    GeneratedUserContent{path='performance-test/cadev-vfull/data/error/errorList.csv'}
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: FAILURE`

**Comment by christian-kreuzberger-dtx** [comment]
Hi @leonvzGit , is this still relevant? 
If so, could you please upgrade to a newer version of Keptn aswell as this jenkins-library as detailed in our [compatibility matrix](https://github.com/keptn-sandbox/keptn-jenkins-library#compatibility-matrix), and verify if the problem still exists?

**Comment by christian-kreuzberger-dtx** [comment]
Cannot reproduce.
